<h1>Cryptography in Freenet</h1>
<ul>
<li>Link-level encryption<br>
 <ul>
 <li>Prevents snooping of inter-node messages
 <li>Messages are quantized to hinder traffic analysis
 <li><i>Traffic analysis still possible, but would be a huge task</i>
</ul>
<li>Document encryption<br>
 <ul>
 <li>Prevents node operators from knowing what data they are caching
 <li><i>Vulnerable to dictionary attack if you have a list of all
     keys</i>
 </ul>
<li>Document verification
 <ul>
 <li>Allow documents in Freenet to be authenticated
 <li>Facilitate secure date-based publishing
 </ul>
</ul>
