<h1>It's a small world after all</h1>
The Milgram Study
<ul>
<li>Letters given to 150 random starting people in Omaha, NB,
and Wichita, KA
<li>Letters had name and address of a target person in Cambridge, MA
<li>Participants instructed to send letter to a friend they know on a 
first-basis most likely to know target person
<li>Particpants asked to write their name on the letter to prevent loops 
and track the letter's path
</ul>
